POST http://localhost:6553/api/admin/getBydepartment
Content-Type: application/json

{
    "Username":"09018316","Department":"09"
}

###测试修改信息
POST http://localhost:6553/api/admin/reset
Content-Type: application/json

{
    "Username":"71118118",
    "Name":"任栗晗",
    "Password":"213183580"
}

###测试获取院系
GET http://localhost:6553/api/admin/get_alldepartments
Content-Type: application/json