
### 测试开始答题
POST http://localhost:6553/api/student/start
Content-Type: application/json

{
    "Name":"任栗晗",
    "Username":"71118118"
}

### 测试获取试卷
GET http://localhost:6553/api/student/result
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6IjAiLCJ1c2VybmFtZSI6IjcxMTE4MTE4Iiwic2NvcmUiOjQsImlhdCI6MTU2NDk3NjYxNCwiZXhwIjoxNTY0OTgwMjE0fQ.1nAmCdy1ng7eNKgZiiMFAY5YK4dfBgU6d15_nEEIsV4
