### 测试登陆功能


POST  http://localhost:6553/api/ui/login
Content-Type: application/json

{
    "Identity":"1",
    "Username":"71118118",
    "Password":"213183580"
}
###
GET http://localhost:6553/api/ui/redis

### 测试get_admin

get http://localhost:5000/api/ui/getadminall

### 测试get_student
GET http://localhost:5000/api/ui/getstudentall

### 测试注册
post http://localhost:5000/api/ui/register
Content-Type: application/json

{
    "Identity":"0",
    "Username":"09018316",
    "Password":"213181432",
    "Name":"黄开鸿"
}






